In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
#NumPy's main datatype is ndarray, which is a N-dimensional array
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int64')

In [17]:
ones = np.ones((2, 3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[1, 1, 6, 1, 5],
       [0, 0, 9, 3, 3],
       [6, 2, 5, 1, 7]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.9955977 , 0.94182578, 0.61484865],
       [0.73017429, 0.6467476 , 0.11465097],
       [0.66712903, 0.92465459, 0.15411881],
       [0.45858963, 0.63796442, 0.50727748],
       [0.25202492, 0.47186079, 0.62847906]])

In [28]:
random_array_2.shape

(5, 3)

In [29]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.15751414, 0.52005666, 0.22870083],
       [0.00491556, 0.55945282, 0.8618588 ],
       [0.14509036, 0.24828445, 0.24892052],
       [0.02751551, 0.34226669, 0.97108214],
       [0.81838839, 0.55410021, 0.96445299]])

In [30]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [31]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [32]:
random_array_5  = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [33]:
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

## 3. Viewing arrays and matrices

In [34]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [35]:
a1

array([1, 2, 3])

In [36]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [37]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [38]:
a1[0]

1

In [39]:
a2.shape

(2, 3)

In [40]:
a2[0]

array([1. , 2. , 3.3])

In [41]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [43]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [44]:
a2[1]

array([4. , 5. , 6.5])

In [45]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [46]:
a3.shape

(2, 3, 3)

In [47]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [48]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [49]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [50]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])

## 4. Manipulating & Comparing Arrays

### Arithmetic

In [52]:
a1

array([1, 2, 3])

In [54]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [55]:
a1 + ones

array([2., 3., 4.])

In [56]:
a1 - ones

array([0., 1., 2.])

In [57]:
a1 * ones

array([1., 2., 3.])

In [58]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [59]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [63]:
a3
a3.shape

(2, 3, 3)

In [68]:
# How can you reshape a2 to be compatible with a3?
# Search: "How to reshape numpy array"
# reshape a2 to (2,3,3)
np.reshape(a2, (2, 3, 1)) * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [69]:
a1 / ones

array([1., 2., 3.])

In [70]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [71]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [72]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [73]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [74]:
np.add(a1, ones)

array([2., 3., 4.])

Use either np.square or x ** y, depending on which workflow you prefer

In [75]:
a1 % 2

array([1, 0, 1])

In [77]:
a1 / 2

array([0.5, 1. , 1.5])

In [78]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [79]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [80]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

In [81]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [82]:
sum(listy_list)

6

In [83]:
a1

array([1, 2, 3])

In [84]:
type(a1)

numpy.ndarray

In [85]:
sum(a1)

6

In [86]:
np.sum(a1)

6

Main difference between `sum(x)` and `np.sum(x)` is that you use Python methods on Python datatypes and NumPy methods on NumPy arrays.

In [87]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [88]:
massive_array[:10]

array([0.62342345, 0.62955693, 0.9099729 , 0.96251949, 0.5850998 ,
       0.16489774, 0.39159332, 0.94455493, 0.34339118, 0.70507037])

In [90]:
# # Jupyter notebook magic function
# %timeit sum(massive_array) # Python's sum()
# %timeit np.sum(massive_array) # NumPy's np.sum()
# # 9.98 ms ± 172 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
# # 50.7 µs ± 2.16 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
# # NumPy's method is about 500x faster

In [91]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [92]:
np.mean(a2)

3.6333333333333333

In [93]:
np.max(a2)

6.5

In [94]:
np.min(a2)

1.0

In [95]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

1.8226964152656422

In [96]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [97]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422